package com.custmanager.view;


import com.custmanager.CustFrame;
import com.custmanager.images.ImagesDir;
import java.awt.event.ActionListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Inderjit
 */
public class LoginView extends AbstractViewDialog {

    private static final long serialVersionUID = 1L;

    public LoginView(CustFrame parent, boolean modal) {
        super(parent, modal);
        super.setResizable(false);
        initComponents();
        init();

    }

    public LoginView() {
        this(new CustFrame(), true);
    }

    public void addButtonController(ActionListener buttonController) {
        loginButton.addActionListener(buttonController);
        cancelButton.addActionListener(buttonController);
    }

    private void init() {
        super.setIconImage(ImagesDir.getImage("elegant.png").getImage());
        super.rootPane.setDefaultButton(loginButton);        
        loginButton.setIcon(ImagesDir.getImage("login.gif"));
        cancelButton.setIcon(ImagesDir.getImage("exit.png"));
        forgotButton.setIcon(ImagesDir.getImage("forgot.png"));
        regButton.setIcon(ImagesDir.getImage("registration.gif"));
        connectServerCombo.removeAllItems();
        connectServerCombo.addItem("ElegantServers");
        PlainDocument document = (PlainDocument) passWord.getDocument();
        document.setDocumentFilter(new DocumentFilter() {

            @Override
            public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String string = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;

                if (string.length() <= 30) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
        loginName.setAllowSpaceSymbol(false);
        forgotButton.setVisible(false);
        regButton.setVisible(false);

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new com.inder.customcomponents.CustomButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        loginButton = new com.inder.customcomponents.CustomButton();
        cancelButton = new com.inder.customcomponents.CustomButton();
        forgotButton = new com.inder.customcomponents.CustomButton();
        regButton = new com.inder.customcomponents.CustomButton();
        loginName = new com.inder.customcomponents.ITextField(30,false,false,false);
        passWord = new com.inder.customcomponents.CustomPasswordField();
        connectServerCombo = new com.inder.customcomponents.CustomComboBox();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elegant Inventory - SignIn Panel");
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(450, 125));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setDisplayedMnemonic('l');
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setLabelFor(loginName);
        jLabel1.setText("Enter Login ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setDisplayedMnemonic('p');
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Enter PassPhrase");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Connect To");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel3, gridBagConstraints);

        errorLabel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        errorLabel.setMinimumSize(new java.awt.Dimension(100, 22));
        errorLabel.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(errorLabel, gridBagConstraints);

        loginButton.setMnemonic('s');
        loginButton.setText("SignIn");
        loginButton.setToolTipText("SignIn with User Name and PassPhrase");
        loginButton.setActionCommand("signIn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(loginButton, gridBagConstraints);

        cancelButton.setMnemonic('c');
        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Exit Login");
        cancelButton.setActionCommand("cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 220);
        getContentPane().add(cancelButton, gridBagConstraints);

        forgotButton.setMnemonic('f');
        forgotButton.setText("Password");
        forgotButton.setToolTipText("Forgotten Password. Click Here");
        forgotButton.setActionCommand("password");
        forgotButton.setMaximumSize(new java.awt.Dimension(135, 25));
        forgotButton.setMinimumSize(new java.awt.Dimension(135, 25));
        forgotButton.setPreferredSize(new java.awt.Dimension(135, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(forgotButton, gridBagConstraints);

        regButton.setMnemonic('n');
        regButton.setText("New Registration");
        regButton.setToolTipText("Fill Reg Form and Submit");
        regButton.setActionCommand("newRegistration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 220);
        getContentPane().add(regButton, gridBagConstraints);

        loginName.setBackground(new java.awt.Color(251, 243, 243));
        loginName.setToolTipText("30 Alpha Numerica Characters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 120);
        getContentPane().add(loginName, gridBagConstraints);

        passWord.setBackground(new java.awt.Color(251, 243, 243));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 120);
        getContentPane().add(passWord, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 120);
        getContentPane().add(connectServerCombo, gridBagConstraints);

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.inder.customcomponents.CustomButton cancelButton;
    public com.inder.customcomponents.CustomComboBox connectServerCombo;
    public javax.swing.JLabel errorLabel;
    public com.inder.customcomponents.CustomButton forgotButton;
    private com.inder.customcomponents.CustomButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public com.inder.customcomponents.CustomButton loginButton;
    public com.inder.customcomponents.ITextField loginName;
    public com.inder.customcomponents.CustomPasswordField passWord;
    public com.inder.customcomponents.CustomButton regButton;
    // End of variables declaration//GEN-END:variables

    @Override
    void updateFieldsOnView() {
// nothing to update on this view
    }

}
